### ISSUE TITLE
歌詞が登録されていない場合、IndexErrorが発生する

### ISSUE THREAD

**Issue by NaoY-2501** [NaoY-2501/fetch_random_lyrics#7]
歌詞が登録されていないアーティストを指定すると、`IndexError` が発生する。
e.g.

`$ python fetch_lyrics.py annabel`

```
Traceback (most recent call last):
  File "fetch_lyrics.py", line 102, in <module>
    main()
  File "fetch_lyrics.py", line 89, in main
    random_song = random.choice([song for song in songs_dict.keys()])
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
(fetch_lyrics) nao-Mac:fetch_lyrics nao$ python fetch_lyrics.py eufonius
Traceback (most recent call last):
  File "fetch_lyrics.py", line 102, in <module>
    main()
  File "fetch_lyrics.py", line 89, in main
    random_song = random.choice([song for song in songs_dict.keys()])
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by NaoY-2501** [comment]
対応したのでクローズ
